version: "3"

tasks:
  run:
    desc: Run the youtube2csv program.
    cmd: go run main.go --secret=./input/client_secret.json --token=./input/token.json --channel-id={{ .CLI_ARGS }}

  lint:
    desc: Check the Go code complies with the rules.
    cmd: golangci-lint run -v

  test:
    desc: Test Go app.
    cmd: go test -v -shuffle=on ./...

  tidy:
    desc: Tidy Go module.
    cmd: go mod tidy

  gen:
    status:
      - test -f .env
    cmds:
      - cp -n .env.example .env

  default:
    desc: Show command list.
    cmd: task -l --sort none
