version: "3"

tasks:
  run:
    desc: Run the youtube2csv program.
    cmd: go run main.go --secret=./input/client_secret.json --token=./input/token.json --channel-id={{ .CLI_ARGS }}

  gen:
    desc: Generate Go code.
    cmd: go generate ./...

  lint:
    desc: Check the Go code complies with the rules.
    cmd: go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0 run -v

  test:
    desc: Test Go app.
    cmd: go test -v -shuffle=on ./...

  tidy:
    desc: Tidy Go module.
    cmd: go mod tidy

  default:
    desc: Show command list.
    cmd: task -l --sort none
