name: golangci-lint

on:
  push:
    paths:
      - ".github/workflows/golangci-lint.yml"
      - ".golangci.yml"
      - "**.go"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
