name: hadolint

on:
  push:
    paths:
      - ".github/workflows/hadolint.yml"
      - "**/Dockerfile*"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
