name: "test-go"

on:
  push:
    paths:
      - ".github/workflows/test-go.yml"
      - "**.go"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run
        run: go test -v -shuffle=on ./...
